# Generated by Django 5.1 on 2025-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='organisation',
            new_name='user',
        ),
    ]
