# Generated by Django 5.1 on 2025-01-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_organisation_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='owner',
        ),
    ]
