# Generated by Django 5.1 on 2025-01-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_organisation_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='image',
            new_name='logo',
        ),
    ]
