# Generated by Django 5.1 on 2025-01-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('opportunity_url', models.URLField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_open', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('is_archive', models.BooleanField()),
                ('attendance_mode', models.CharField(choices=[('ONLINE', 'Online'), ('FACE_TO_FACE', 'Face to Face')], max_length=20)),
                ('location', models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], default='WA', max_length=3)),
                ('discipline', models.ManyToManyField(related_name='opportunities', to='opportunities.discipline')),
                ('eligibility', models.ManyToManyField(related_name='opportunities', to='opportunities.eligibility')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('type', models.ManyToManyField(related_name='opportunities', to='opportunities.type')),
            ],
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_by_applicants', to='opportunities.opportunity')),
            ],
            options={
                'unique_together': {('applicant', 'opportunity')},
            },
        ),
    ]
