# Generated by Django 5.1 on 2025-01-31 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_by_applicants', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='type',
            field=models.ManyToManyField(related_name='opportunities', to='opportunities.type'),
        ),
        migrations.AlterUniqueTogether(
            name='savedopportunity',
            unique_together={('applicant', 'opportunity')},
        ),
    ]
