# Generated by Django 5.1 on 2025-01-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_archieve',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
