# Generated by Django 5.1 on 2025-01-22 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_savedopportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedopportunity',
            old_name='applicant',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='savedopportunity',
            unique_together={('owner', 'opportunity')},
        ),
    ]
