# Generated by Django 5.1 on 2025-01-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_is_archieve'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='attendence_mode',
            new_name='attendance_mode',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='is_archieve',
            new_name='is_archive',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='users.organisation'),
        ),
    ]
