# Generated by Django 5.1 on 2025-01-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_rename_attendence_mode_opportunity_attendance_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='organisation',
        ),
    ]
