# Generated by Django 5.1 on 2025-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_rename_applicant_savedopportunity_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedopportunity',
            name='discipline',
            field=models.ManyToManyField(related_name='saved_opportunities', to='opportunities.discipline'),
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='eligibility',
            field=models.ManyToManyField(related_name='saved_opportunities', to='opportunities.eligibility'),
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='type',
            field=models.ManyToManyField(related_name='saved_opportunities', to='opportunities.type'),
        ),
    ]
