# Generated by Django 5.1 on 2025-01-22 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_savedopportunity_discipline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedopportunity',
            old_name='owner',
            new_name='applicant',
        ),
        migrations.AlterUniqueTogether(
            name='savedopportunity',
            unique_together={('applicant', 'opportunity')},
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='opportunity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='opportunities.opportunity'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='savedopportunity',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='savedopportunity',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='savedopportunity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='savedopportunity',
            name='type',
        ),
    ]
