# Generated by Django 5.1 on 2025-01-22 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_rename_owner_savedopportunity_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedopportunity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_by_applicants', to='opportunities.opportunity'),
        ),
    ]
