# Generated by Django 5.1 on 2025-01-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_alter_savedopportunity_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedopportunity',
            name='opportunity_ptr',
        ),
        migrations.AddField(
            model_name='savedopportunity',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
